// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: chat.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MSG int32

const (
	MSG_M_CMEnterWorld    MSG = 0
	MSG_M_SMEnterWorld    MSG = 1
	MSG_M_CMCreatePlayer  MSG = 2
	MSG_M_SMCreatePlayer  MSG = 3
	MSG_M_CMBroadcastChat MSG = 4
	MSG_M_SMBroadcastChat MSG = 5
	MSG_M_CMHistoryChat   MSG = 6
	MSG_M_SMHistoryChat   MSG = 7
	MSG_M_CMAllPlayers    MSG = 8
	MSG_M_SMAllPlayers    MSG = 9
	MSG_M_CMPrivateChat   MSG = 10
	MSG_M_SMPrivateChat   MSG = 11
)

// Enum value maps for MSG.
var (
	MSG_name = map[int32]string{
		0:  "M_CMEnterWorld",
		1:  "M_SMEnterWorld",
		2:  "M_CMCreatePlayer",
		3:  "M_SMCreatePlayer",
		4:  "M_CMBroadcastChat",
		5:  "M_SMBroadcastChat",
		6:  "M_CMHistoryChat",
		7:  "M_SMHistoryChat",
		8:  "M_CMAllPlayers",
		9:  "M_SMAllPlayers",
		10: "M_CMPrivateChat",
		11: "M_SMPrivateChat",
	}
	MSG_value = map[string]int32{
		"M_CMEnterWorld":    0,
		"M_SMEnterWorld":    1,
		"M_CMCreatePlayer":  2,
		"M_SMCreatePlayer":  3,
		"M_CMBroadcastChat": 4,
		"M_SMBroadcastChat": 5,
		"M_CMHistoryChat":   6,
		"M_SMHistoryChat":   7,
		"M_CMAllPlayers":    8,
		"M_SMAllPlayers":    9,
		"M_CMPrivateChat":   10,
		"M_SMPrivateChat":   11,
	}
)

func (x MSG) Enum() *MSG {
	p := new(MSG)
	*p = x
	return p
}

func (x MSG) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSG) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (MSG) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x MSG) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSG.Descriptor instead.
func (MSG) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

type CMEnterWorld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CMEnterWorld) Reset() {
	*x = CMEnterWorld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMEnterWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMEnterWorld) ProtoMessage() {}

func (x *CMEnterWorld) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMEnterWorld.ProtoReflect.Descriptor instead.
func (*CMEnterWorld) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

type SMEnterWorld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SMEnterWorld) Reset() {
	*x = SMEnterWorld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMEnterWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMEnterWorld) ProtoMessage() {}

func (x *SMEnterWorld) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMEnterWorld.ProtoReflect.Descriptor instead.
func (*SMEnterWorld) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

//C->M创建角色
type CMCreatePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CMCreatePlayer) Reset() {
	*x = CMCreatePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMCreatePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMCreatePlayer) ProtoMessage() {}

func (x *CMCreatePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMCreatePlayer.ProtoReflect.Descriptor instead.
func (*CMCreatePlayer) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *CMCreatePlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//M->C创建角色的返回
type SMCreatePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SMCreatePlayer) Reset() {
	*x = SMCreatePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMCreatePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMCreatePlayer) ProtoMessage() {}

func (x *SMCreatePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMCreatePlayer.ProtoReflect.Descriptor instead.
func (*SMCreatePlayer) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *SMCreatePlayer) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SMCreatePlayer) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

//广播的消息
type CMBroadcastChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chatdata string `protobuf:"bytes,2,opt,name=chatdata,proto3" json:"chatdata,omitempty"`
}

func (x *CMBroadcastChat) Reset() {
	*x = CMBroadcastChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMBroadcastChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMBroadcastChat) ProtoMessage() {}

func (x *CMBroadcastChat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMBroadcastChat.ProtoReflect.Descriptor instead.
func (*CMBroadcastChat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *CMBroadcastChat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CMBroadcastChat) GetChatdata() string {
	if x != nil {
		return x.Chatdata
	}
	return ""
}

//给各客户端的广播消息
type SMBroadcastChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time     string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Chatdata string `protobuf:"bytes,4,opt,name=chatdata,proto3" json:"chatdata,omitempty"`
}

func (x *SMBroadcastChat) Reset() {
	*x = SMBroadcastChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMBroadcastChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMBroadcastChat) ProtoMessage() {}

func (x *SMBroadcastChat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMBroadcastChat.ProtoReflect.Descriptor instead.
func (*SMBroadcastChat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *SMBroadcastChat) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SMBroadcastChat) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *SMBroadcastChat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SMBroadcastChat) GetChatdata() string {
	if x != nil {
		return x.Chatdata
	}
	return ""
}

//请求历史聊天记录
type CMHistoryChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CMHistoryChat) Reset() {
	*x = CMHistoryChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMHistoryChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMHistoryChat) ProtoMessage() {}

func (x *CMHistoryChat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMHistoryChat.ProtoReflect.Descriptor instead.
func (*CMHistoryChat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

//历史聊天记录的返回
type SMHistoryChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg []*SMBroadcastChat `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SMHistoryChat) Reset() {
	*x = SMHistoryChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMHistoryChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMHistoryChat) ProtoMessage() {}

func (x *SMHistoryChat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMHistoryChat.ProtoReflect.Descriptor instead.
func (*SMHistoryChat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *SMHistoryChat) GetMsg() []*SMBroadcastChat {
	if x != nil {
		return x.Msg
	}
	return nil
}

//玩家列表请求
type CMAllPlayers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CMAllPlayers) Reset() {
	*x = CMAllPlayers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMAllPlayers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMAllPlayers) ProtoMessage() {}

func (x *CMAllPlayers) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMAllPlayers.ProtoReflect.Descriptor instead.
func (*CMAllPlayers) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

type SMAllPlayers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *SMAllPlayers) Reset() {
	*x = SMAllPlayers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMAllPlayers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMAllPlayers) ProtoMessage() {}

func (x *SMAllPlayers) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMAllPlayers.ProtoReflect.Descriptor instead.
func (*SMAllPlayers) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *SMAllPlayers) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

//私密聊天
type CMPrivateChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chat string `protobuf:"bytes,2,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *CMPrivateChat) Reset() {
	*x = CMPrivateChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMPrivateChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMPrivateChat) ProtoMessage() {}

func (x *CMPrivateChat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMPrivateChat.ProtoReflect.Descriptor instead.
func (*CMPrivateChat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *CMPrivateChat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CMPrivateChat) GetChat() string {
	if x != nil {
		return x.Chat
	}
	return ""
}

type SMPrivateChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Chatdata string `protobuf:"bytes,3,opt,name=chatdata,proto3" json:"chatdata,omitempty"`
}

func (x *SMPrivateChat) Reset() {
	*x = SMPrivateChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMPrivateChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMPrivateChat) ProtoMessage() {}

func (x *SMPrivateChat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMPrivateChat.ProtoReflect.Descriptor instead.
func (*SMPrivateChat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *SMPrivateChat) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *SMPrivateChat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SMPrivateChat) GetChatdata() string {
	if x != nil {
		return x.Chatdata
	}
	return ""
}

var File_chat_proto protoreflect.FileDescriptor

var file_chat_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x4d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x4d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x22, 0x24, 0x0a, 0x0e, 0x43, 0x4d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x0e, 0x53, 0x4d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x41, 0x0a, 0x0f, 0x43, 0x4d,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x74, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x64, 0x61, 0x74, 0x61, 0x22, 0x65, 0x0a,
	0x0f, 0x53, 0x4d, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x74,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x4d, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x43, 0x68, 0x61, 0x74, 0x22, 0x36, 0x0a, 0x0d, 0x53, 0x4d, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x43, 0x68, 0x61, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x4d, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0e, 0x0a,
	0x0c, 0x43, 0x4d, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x24, 0x0a,
	0x0c, 0x53, 0x4d, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x22, 0x37, 0x0a, 0x0d, 0x43, 0x4d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0x53, 0x0a, 0x0d,
	0x53, 0x4d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x74, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x64, 0x61, 0x74,
	0x61, 0x2a, 0x83, 0x02, 0x0a, 0x03, 0x4d, 0x53, 0x47, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x5f, 0x43,
	0x4d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x4d, 0x5f, 0x53, 0x4d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x10,
	0x01, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x5f, 0x43, 0x4d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x5f, 0x53, 0x4d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x10, 0x03, 0x12, 0x15, 0x0a,
	0x11, 0x4d, 0x5f, 0x43, 0x4d, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x43, 0x68,
	0x61, 0x74, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x5f, 0x53, 0x4d, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x4d,
	0x5f, 0x43, 0x4d, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x68, 0x61, 0x74, 0x10, 0x06,
	0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x5f, 0x53, 0x4d, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x43,
	0x68, 0x61, 0x74, 0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x5f, 0x43, 0x4d, 0x41, 0x6c, 0x6c,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x10, 0x08, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x5f, 0x53,
	0x4d, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x10, 0x09, 0x12, 0x13, 0x0a,
	0x0f, 0x4d, 0x5f, 0x43, 0x4d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74,
	0x10, 0x0a, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x5f, 0x53, 0x4d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x10, 0x0b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData = file_chat_proto_rawDesc
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_proto_rawDescData)
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_chat_proto_goTypes = []interface{}{
	(MSG)(0),                // 0: pb.MSG
	(*CMEnterWorld)(nil),    // 1: pb.CMEnterWorld
	(*SMEnterWorld)(nil),    // 2: pb.SMEnterWorld
	(*CMCreatePlayer)(nil),  // 3: pb.CMCreatePlayer
	(*SMCreatePlayer)(nil),  // 4: pb.SMCreatePlayer
	(*CMBroadcastChat)(nil), // 5: pb.CMBroadcastChat
	(*SMBroadcastChat)(nil), // 6: pb.SMBroadcastChat
	(*CMHistoryChat)(nil),   // 7: pb.CMHistoryChat
	(*SMHistoryChat)(nil),   // 8: pb.SMHistoryChat
	(*CMAllPlayers)(nil),    // 9: pb.CMAllPlayers
	(*SMAllPlayers)(nil),    // 10: pb.SMAllPlayers
	(*CMPrivateChat)(nil),   // 11: pb.CMPrivateChat
	(*SMPrivateChat)(nil),   // 12: pb.SMPrivateChat
}
var file_chat_proto_depIdxs = []int32{
	6, // 0: pb.SMHistoryChat.msg:type_name -> pb.SMBroadcastChat
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMEnterWorld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMEnterWorld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMCreatePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMCreatePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMBroadcastChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMBroadcastChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMHistoryChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMHistoryChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMAllPlayers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMAllPlayers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMPrivateChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMPrivateChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_rawDesc = nil
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
